### ISSUE TITLE
Missing HDU's

### ISSUE THREAD

**Issue by carbinefreak** [boatbod/op25#39]
It seems like OP25 misses most (90%+) of the HDUs, I originally thought it was a SDR problem but I just purchased an airspy R2 and the issue persists. I found a duplicate issues in osmocom -> https://osmocom.org/issues/2172

**Comment by boatbod** [comment]
It's not an application problem per-se, but the speed (or lack thereof) at which re-tuning to a voice channel takes place.  Figure 500-700msec for a tune and resync of the demodulator & frame assembler before communication is reestablished, so many times the HDU will be gone before we get there.

Since my fork of op25 uses essentially the same demod & framer as osmocom, it's not surprising they exhibit the same behavior.
