### ISSUE TITLE
Unit ID lagging during Phase II communications

### ISSUE THREAD

**Issue by JoeyAbsi** [boatbod/op25#74]
When a conversations is initiated in Phase II, the unit ID will remain the same even if another user is talking (i. e. user 1 and 2 are talking, the unit ID displayed is the one of user 1 (if the talks first) even if there's a back and forth between users).

Sometimes, the unit ID won't show up. Both of the issues are happening to OP25 and my Uniden 436HP and happen only in Phase II.

**Comment by boatbod** [comment]
The Unit ID (srcaddr) is received by the P25 decoder and passed up to the trunking module and then on to the terminal module whenever one is seen.  There is however a potential latency issue because the terminal module only requests updates about once per second.  

A lot also depends on the source data;  if op25 tunes to the voice channel quickly enough to catch the MAC_PTT (or HDU) it may get the srcaddr more quickly than if it enters late and has to wait for a voice update containing the srcaddr.  If you turn up logging to -v 5 you'll see a lot of "set tgid" messages containing "srcaddr=0", which basically means the information is not available at that point in time.
