### ISSUE TITLE
pulse does not work from service

### ISSUE THREAD

**Issue by hayden-t** [boatbod/op25#81]
-O pulse
works when run from terminal, but when via service

Nov 30 07:56:32 trunker bash[1852]: audio device: pulse
Nov 30 07:56:32 trunker bash[1852]: 11/30/20 07:56:32.873946 Could not open PulseAudio stream: No such device or address
Nov 30 07:56:32 trunker bash[1852]: Listening on 127.0.0.1:23456
Nov 30 07:56:32 trunker bash[1852]: Allocating 15 zero-copy buffers
Nov 30 07:56:35 trunker bash[1852]: Assertion 'p' failed at pulse/simple.c:386, function pa_simple_drain(). Aborting.
Nov 30 07:56:35 trunker bash[1852]: op25.sh: line 1:  1853 Aborted                                                       ./rx.py --args 'rtl' -N 'LNA:35' -S 250000 -d 0 -V -w -f xxxxx -D fsk4 -                                      U -O pulse -l http:0.0.0.0:12345
Nov 30 07:56:35 trunker systemd[1]: op25-rx.service: Main process exited, code=e                                      xited, status=134/n/a
Nov 30 07:56:35 trunker systemd[1]: op25-rx.service: Failed with result 'exit-co                                      de'.

**Comment by boatbod** [comment]
The Pulse Audio service is often started at login by the desktop window manager.  When running op25 as a service on a headless system you frequently have to jump through considerable hoops to get pulse running before op25.  This seems particularly bad on RPi4 and I'm not sure I can adequately explain how to do it.  Mostly in headless environments you probably would be streaming rather than playing local audio so it's not generally a big deal.
